name: Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Example
        run: |
          chmod +x $(ls ./examples/**/*.sh)
          find ./examples -type f -name "*.sh" -print0 | xargs -0 -I {} bash "{}"
          ls -ral bin

      - name: Test Build Output Binaries
        run: |
          rm ./bin/weblet_*
          find ./bin -type f -executable -exec {} \;
